server:
  port: 10004

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://gungnirUser:Gungnir-123456@localhost/gungnir
  jackson:
    default-property-inclusion: non_null

upload:
  path: upload

repository:
  base-dir: repository

socket:
  port: 6300

job:
  pool-num: 10
  wait-for-timeouts:  30

xxl:
  job:
    appName: gungirJobExecutor
    admin:
      addresses: http://localhost:8082/xxl-job-admin
    accessToken: Gungnir123!
    executor:
      logpath: logs
      logretentiondays: 5

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://cherry_discovery_local:local123@127.0.0.1:10002/eureka/
